config/routes.rb
Rails.application.routes.draw do
  
  resources :contacts
  resources :accounts
  devise_for :users

  root 'contacts#index'

  devise_scope :user do
    authenticated :user do
      root 'accounts#new', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /accounts
  # GET /accounts.json
  def index
    if !Account.find_by(user: current_user.id, level: "Boss")
      redirect_to contacts_url
    end
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @Account
    if !Account.exists?
      @account = Account.new(user: current_user.id, level: "Boss")
      @account.save
    elsif !Account.find_by(user: current_user.id)
      @account = Account.new(user: current_user.id, level: "Applicant")
      @account.save
    end
    sign_out_and_redirect(current_user)
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    if !Account.find_by(user: current_user.id, level: "Boss")
      redirect_to contacts_url
    end
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
    if !Account.find_by(user: current_user.id, level: "Boss")
      redirect_to contacts_url
    elsif @account.level == "Applicant"
      @account.level = "Employee"
      @account.save
    end
    redirect_to accounts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:user, :level)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /contacts
  # GET /contacts.json
  def index
    if !Account.find_by(user: current_user.id, level: "Boss")
      if !Account.find_by(user: current_user.id, level: "Employee")
        redirect_to new_account_url
      end
    end
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    if !Account.find_by(user: current_user.id, level: "Boss")
      if !Account.find_by(user: current_user.id, level: "Employee")
        sign_out_and_redirect(current_user)
      end
    end
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
    if !Account.find_by(user: current_user.id, level: "Boss")
      if !Account.find_by(user: current_user.id, level: "Employee")
        redirect_to new_account_url
      end
    end
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    if !Account.find_by(user: current_user.id, level: "Boss")
      if !Account.find_by(user: current_user.id, level: "Employee")
        redirect_to new_account_url
      end
    end
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    if !Account.find_by(user: current_user.id, level: "Boss")
      if !Account.find_by(user: current_user.id, level: "Employee")
        redirect_to new_account_url
      end
    end
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:number, :name, :comments)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= User.find(account.user).email %></td>
        <td><%= account.level %></td>
        <% if account.level == 'Applicant' %>
          <td><%= link_to 'Approve', edit_account_path(account) %></td>
        <% end %>
        <% if account.level != 'Boss' %>
          <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_field :comments %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Contacts</h2>
<center><%= link_to 'New Contact', new_contact_path %></center>

<br>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Number</th>
      <th>Name</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.id %></td>
        <td><%= contact.number %></td>
        <td><%= contact.name %></td>
        <td><%= contact.comments %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @contact.number %>
</p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @contact.comments %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LS Call Center</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
	<nav class="navbar navbar-inverse">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="#">LS Call Center</a>
	    </div>
	    <ul class="nav navbar-nav">
	      <% if user_signed_in? %>
		      <li class="active"><a href="/">Contacts</a></li>
		      <% if Account.find_by(user: current_user, level: 'Boss') %>
		      <li class="active">
		      	<%= link_to('Accounts', accounts_url) %>
		      </li>
		      <% end %>
		      <li>
		 		<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
		      </li>
	      <% end %>
	    </ul>
	  </div>
	</nav>
	<div class="content">
		<p class="notice"><%= alert %></p>
		<%= yield %>
	</div>

</body>
</html>